var hierarchy =
[
    [ "jnsc::AllpassFilter< T, Interpolator >", "classjnsc_1_1AllpassFilter.html", null ],
    [ "jnsc::AudioBuffer< T, Layout >", "classjnsc_1_1AudioBuffer.html", null ],
    [ "jnsc::AudioBuffer< T, BufferLayout::Interleaved >", "classjnsc_1_1AudioBuffer_3_01T_00_01BufferLayout_1_1Interleaved_01_4.html", null ],
    [ "jnsc::AudioBuffer< T, BufferLayout::Planar >", "classjnsc_1_1AudioBuffer_3_01T_00_01BufferLayout_1_1Planar_01_4.html", null ],
    [ "jnsc::BiquadFilter< T, Topology, Design, RoutingType >", "classjnsc_1_1BiquadFilter.html", null ],
    [ "jnsc::AudioBuffer< T, BufferLayout::Planar >::ChannelProxy", "classjnsc_1_1AudioBuffer_3_01T_00_01BufferLayout_1_1Planar_01_4_1_1ChannelProxy.html", null ],
    [ "jnsc::BiquadFilter< T, Topology, Design, RoutingType >::ChannelProxy", "classjnsc_1_1BiquadFilter_1_1ChannelProxy.html", null ],
    [ "jnsc::OnePoleFilter< T, Topology, Design, RoutingType >::ChannelProxy", "classjnsc_1_1OnePoleFilter_1_1ChannelProxy.html", null ],
    [ "jnsc::BiquadFilter< T, Topology, Design, RoutingType >::ChannelSectionProxy", "classjnsc_1_1BiquadFilter_1_1ChannelSectionProxy.html", null ],
    [ "jnsc::OnePoleFilter< T, Topology, Design, RoutingType >::ChannelSectionProxy", "classjnsc_1_1OnePoleFilter_1_1ChannelSectionProxy.html", null ],
    [ "jnsc::CircularAudioBuffer< T >", "classjnsc_1_1CircularAudioBuffer.html", null ],
    [ "jnsc::CombFilter< T, Interpolator >", "classjnsc_1_1CombFilter.html", null ],
    [ "jnsc::effects::Compressor< T >", "classjnsc_1_1effects_1_1Compressor.html", null ],
    [ "jnsc::AudioBuffer< T, BufferLayout::Planar >::ConstChannelProxy", "classjnsc_1_1AudioBuffer_3_01T_00_01BufferLayout_1_1Planar_01_4_1_1ConstChannelProxy.html", null ],
    [ "jnsc::AudioBuffer< T, BufferLayout::Interleaved >::ConstSampleProxy", "classjnsc_1_1AudioBuffer_3_01T_00_01BufferLayout_1_1Interleaved_01_4_1_1ConstSampleProxy.html", null ],
    [ "jnsc::Crossfader< T >", "classjnsc_1_1Crossfader.html", null ],
    [ "jnsc::models::DecayFilter< T, DecayType >", "classjnsc_1_1models_1_1DecayFilter.html", null ],
    [ "jnsc::models::DecayFilter< T, models::Shelf1Decay< T > >", "classjnsc_1_1models_1_1DecayFilter.html", null ],
    [ "jnsc::models::DecayFilter< T, Shelf1Decay< T > >", "classjnsc_1_1models_1_1DecayFilter.html", null ],
    [ "jnsc::effects::Delay< T >", "classjnsc_1_1effects_1_1Delay.html", null ],
    [ "jnsc::DelayLine< T, Interpolator >", "classjnsc_1_1DelayLine.html", null ],
    [ "jnsc::DelayLine< T, jnsc::LagrangeInterpolator< T > >", "classjnsc_1_1DelayLine.html", null ],
    [ "jnsc::DelayLine< T, jnsc::LinearInterpolator< T > >", "classjnsc_1_1DelayLine.html", null ],
    [ "jnsc::DelayLine< T, LinearInterpolator< T > >", "classjnsc_1_1DelayLine.html", null ],
    [ "jnsc::effects::Distortion< T >", "classjnsc_1_1effects_1_1Distortion.html", null ],
    [ "jnsc::DryWetMixer< T >", "classjnsc_1_1DryWetMixer.html", null ],
    [ "jnsc::DspParam< T, Type, Order >", "classjnsc_1_1DspParam.html", null ],
    [ "jnsc::models::DynamicsStage< T, EnvelopeType, GainPolicy, GainSmootherType, DetectorType, SideChainFilter, Metering >", "classjnsc_1_1models_1_1DynamicsStage.html", null ],
    [ "jnsc::EnvelopeFollower< T, Type >", "classjnsc_1_1EnvelopeFollower.html", null ],
    [ "jnsc::EnvelopeFollower< T, EnvelopeType::Peak >", "classjnsc_1_1EnvelopeFollower_3_01T_00_01EnvelopeType_1_1Peak_01_4.html", null ],
    [ "jnsc::EnvelopeFollower< T, EnvelopeType::RMS >", "classjnsc_1_1EnvelopeFollower_3_01T_00_01EnvelopeType_1_1RMS_01_4.html", null ],
    [ "jnsc::effects::Equalizer< T >", "classjnsc_1_1effects_1_1Equalizer.html", null ],
    [ "jnsc::models::FeedbackDelayNetwork< T, M, FeedbackMatrixType, InputMatrixType, OutputMatrixType, DecayType, ModulationSourceType, InterpolatorType >", "classjnsc_1_1models_1_1FeedbackDelayNetwork.html", null ],
    [ "jnsc::models::FeedbackDelayNetwork< T, FDN_SIZE, MixingMatrixType::Householder, MixingMatrixType::DecorrelatedSum, MixingMatrixType::DecorrelatedSum, models::Shelf1Decay< T >, jnsc::models::FilteredNoise< T >, jnsc::LinearInterpolator< T > >", "classjnsc_1_1models_1_1FeedbackDelayNetwork.html", null ],
    [ "jnsc::models::FilteredNoise< T, noiseType, filterType >", "classjnsc_1_1models_1_1FilteredNoise.html", null ],
    [ "jnsc::models::FilteredNoise< T, noiseType, FilterType::Lowpass1stOrder >", "classjnsc_1_1models_1_1FilteredNoise_3_01T_00_01noiseType_00_01FilterType_1_1Lowpass1stOrder_01_4.html", null ],
    [ "jnsc::models::FilteredNoise< T, noiseType, FilterType::Lowpass2ndOrder >", "classjnsc_1_1models_1_1FilteredNoise_3_01T_00_01noiseType_00_01FilterType_1_1Lowpass2ndOrder_01_4.html", null ],
    [ "jnsc::effects::Flanger< T >", "classjnsc_1_1effects_1_1Flanger.html", null ],
    [ "jnsc::Frequency< T >", "structjnsc_1_1Frequency.html", null ],
    [ "jnsc::Gain< T >", "structjnsc_1_1Gain.html", null ],
    [ "jnsc::GainComputer< T, Policy >", "classjnsc_1_1GainComputer.html", null ],
    [ "jnsc::GainComputer< T, CompressorPolicy< T > >", "classjnsc_1_1GainComputer.html", null ],
    [ "jnsc::GainSmoother< T, Type >", "classjnsc_1_1GainSmoother.html", null ],
    [ "jnsc::GainSmoother< T, GainSmootherType::AttackRelease >", "classjnsc_1_1GainSmoother_3_01T_00_01GainSmootherType_1_1AttackRelease_01_4.html", null ],
    [ "jnsc::LagrangeInterpolator< T >", "structjnsc_1_1LagrangeInterpolator.html", null ],
    [ "jnsc::LinearInterpolator< T >", "structjnsc_1_1LinearInterpolator.html", null ],
    [ "jnsc::MixingMatrix< T, Type >", "classjnsc_1_1MixingMatrix.html", null ],
    [ "jnsc::MixingMatrix< T, FeedbackMatrixType >", "classjnsc_1_1MixingMatrix.html", null ],
    [ "jnsc::MixingMatrix< T, InputMatrixType >", "classjnsc_1_1MixingMatrix.html", null ],
    [ "jnsc::MixingMatrix< T, MixingMatrixType::DecorrelatedSum >", "classjnsc_1_1MixingMatrix_3_01T_00_01MixingMatrixType_1_1DecorrelatedSum_01_4.html", null ],
    [ "jnsc::MixingMatrix< T, MixingMatrixType::Dense >", "classjnsc_1_1MixingMatrix_3_01T_00_01MixingMatrixType_1_1Dense_01_4.html", null ],
    [ "jnsc::MixingMatrix< T, MixingMatrixType::Hadamard >", "classjnsc_1_1MixingMatrix_3_01T_00_01MixingMatrixType_1_1Hadamard_01_4.html", null ],
    [ "jnsc::MixingMatrix< T, MixingMatrixType::Householder >", "classjnsc_1_1MixingMatrix_3_01T_00_01MixingMatrixType_1_1Householder_01_4.html", null ],
    [ "jnsc::MixingMatrix< T, MixingMatrixType::Identity >", "classjnsc_1_1MixingMatrix_3_01T_00_01MixingMatrixType_1_1Identity_01_4.html", null ],
    [ "jnsc::MixingMatrix< T, OutputMatrixType >", "classjnsc_1_1MixingMatrix.html", null ],
    [ "jnsc::models::ModulatedDelayStage< T, Interpolator, UseInternalLFO, UseDamping, UseCrossFeedback >", "classjnsc_1_1models_1_1ModulatedDelayStage.html", null ],
    [ "jnsc::models::ModulatedDelayStage< T, jnsc::LagrangeInterpolator< T >, false, true, true >", "classjnsc_1_1models_1_1ModulatedDelayStage.html", null ],
    [ "jnsc::models::ModulatedDelayStage< T, jnsc::LagrangeInterpolator< T >, true, false, false >", "classjnsc_1_1models_1_1ModulatedDelayStage.html", null ],
    [ "jnsc::ModulationInput< T >", "structjnsc_1_1ModulationInput.html", [
      [ "jnsc::AllpassMod::Block< T >", "structjnsc_1_1AllpassMod_1_1Block.html", null ],
      [ "jnsc::AllpassMod::Sample< T >", "structjnsc_1_1AllpassMod_1_1Sample.html", null ],
      [ "jnsc::CombMod::Block< T >", "structjnsc_1_1CombMod_1_1Block.html", null ],
      [ "jnsc::CombMod::Sample< T >", "structjnsc_1_1CombMod_1_1Sample.html", null ]
    ] ],
    [ "jnsc::NearestInterpolator< T >", "structjnsc_1_1NearestInterpolator.html", null ],
    [ "jnsc::Noise< T, Type >", "classjnsc_1_1Noise.html", null ],
    [ "jnsc::Noise< T, noiseType >", "classjnsc_1_1Noise.html", null ],
    [ "jnsc::Noise< T, NoiseType::Gaussian >", "classjnsc_1_1Noise_3_01T_00_01NoiseType_1_1Gaussian_01_4.html", null ],
    [ "jnsc::Noise< T, NoiseType::Uniform >", "classjnsc_1_1Noise_3_01T_00_01NoiseType_1_1Uniform_01_4.html", null ],
    [ "jnsc::NoneInterpolator< T >", "structjnsc_1_1NoneInterpolator.html", null ],
    [ "jnsc::OnePoleFilter< T, Topology, Design, RoutingType >", "classjnsc_1_1OnePoleFilter.html", null ],
    [ "jnsc::Oscillator< T >", "classjnsc_1_1Oscillator.html", null ],
    [ "jnsc::OversampledProcessor< T, Factor >", "classjnsc_1_1OversampledProcessor.html", null ],
    [ "jnsc::OversampledProcessor< T, 0 >", "classjnsc_1_1OversampledProcessor_3_01T_00_010_01_4.html", null ],
    [ "jnsc::OversampledProcessor< T, 1 >", "classjnsc_1_1OversampledProcessor.html", null ],
    [ "jnsc::OversampledProcessor< T, OversamplingFactor >", "classjnsc_1_1OversampledProcessor.html", null ],
    [ "jnsc::Oversampler< T, Factor >", "classjnsc_1_1Oversampler.html", null ],
    [ "jnsc::Oversampler< T, 16 >", "classjnsc_1_1Oversampler.html", null ],
    [ "jnsc::Oversampler< T, 2 >", "classjnsc_1_1Oversampler.html", null ],
    [ "jnsc::Oversampler< T, 4 >", "classjnsc_1_1Oversampler.html", null ],
    [ "jnsc::Oversampler< T, 8 >", "classjnsc_1_1Oversampler.html", null ],
    [ "jnsc::Oversampler< T, Factor >", "classjnsc_1_1Oversampler.html", null ],
    [ "jnsc::effects::Reverb< T >", "classjnsc_1_1effects_1_1Reverb.html", null ],
    [ "jnsc::RoutingWrapper< Filter, RoutingType >", "structjnsc_1_1RoutingWrapper.html", null ],
    [ "jnsc::RoutingWrapper< Filter< T, Topology, Design, CurrentRouting >, Routing::Parallel >", "structjnsc_1_1RoutingWrapper_3_01Filter_3_01T_00_01Topology_00_01Design_00_01CurrentRouting_01_4_00_01Routing_1_1Parallel_01_4.html", null ],
    [ "jnsc::RoutingWrapper< Filter< T, Topology, Design, CurrentRouting >, Routing::Series >", "structjnsc_1_1RoutingWrapper_3_01Filter_3_01T_00_01Topology_00_01Design_00_01CurrentRouting_01_4_00_01Routing_1_1Series_01_4.html", null ],
    [ "jnsc::AudioBuffer< T, BufferLayout::Interleaved >::SampleProxy", "classjnsc_1_1AudioBuffer_3_01T_00_01BufferLayout_1_1Interleaved_01_4_1_1SampleProxy.html", null ],
    [ "jnsc::models::SaturationStage< T, ShaperType, PreFilter, PostFilter, OversamplingFactor >", "classjnsc_1_1models_1_1SaturationStage.html", null ],
    [ "jnsc::models::SaturationStage< T, WaveShaperType::Dynamic, true, true, 1 >", "classjnsc_1_1models_1_1SaturationStage.html", null ],
    [ "jnsc::models::SaturationStage< T, WaveShaperType::Dynamic, true, true, OVERSAMPLING_FACTOR >", "classjnsc_1_1models_1_1SaturationStage.html", null ],
    [ "jnsc::BiquadFilter< T, Topology, Design, RoutingType >::SectionProxy", "classjnsc_1_1BiquadFilter_1_1SectionProxy.html", null ],
    [ "jnsc::OnePoleFilter< T, Topology, Design, RoutingType >::SectionProxy", "classjnsc_1_1OnePoleFilter_1_1SectionProxy.html", null ],
    [ "jnsc::Time< T >", "structjnsc_1_1Time.html", null ],
    [ "jnsc::TPTIntegrator< T >", "classjnsc_1_1TPTIntegrator.html", null ],
    [ "jnsc::WaveShaper< T, Type >", "classjnsc_1_1WaveShaper.html", null ],
    [ "jnsc::WaveShaper< T, ShaperType >", "classjnsc_1_1WaveShaper.html", null ],
    [ "jnsc::WaveShaper< T, WaveShaperType::Atan >", "classjnsc_1_1WaveShaper_3_01T_00_01WaveShaperType_1_1Atan_01_4.html", null ],
    [ "jnsc::WaveShaper< T, WaveShaperType::Cubic >", "classjnsc_1_1WaveShaper_3_01T_00_01WaveShaperType_1_1Cubic_01_4.html", null ],
    [ "jnsc::WaveShaper< T, WaveShaperType::Custom >", "classjnsc_1_1WaveShaper_3_01T_00_01WaveShaperType_1_1Custom_01_4.html", null ],
    [ "jnsc::WaveShaper< T, WaveShaperType::Dynamic >", "classjnsc_1_1WaveShaper_3_01T_00_01WaveShaperType_1_1Dynamic_01_4.html", null ],
    [ "jnsc::WaveShaper< T, WaveShaperType::FullWaveRectifier >", "classjnsc_1_1WaveShaper_3_01T_00_01WaveShaperType_1_1FullWaveRectifier_01_4.html", null ],
    [ "jnsc::WaveShaper< T, WaveShaperType::HalfWaveRectifier >", "classjnsc_1_1WaveShaper_3_01T_00_01WaveShaperType_1_1HalfWaveRectifier_01_4.html", null ],
    [ "jnsc::WaveShaper< T, WaveShaperType::HardClip >", "classjnsc_1_1WaveShaper_3_01T_00_01WaveShaperType_1_1HardClip_01_4.html", null ],
    [ "jnsc::WaveShaper< T, WaveShaperType::None >", "classjnsc_1_1WaveShaper_3_01T_00_01WaveShaperType_1_1None_01_4.html", null ],
    [ "jnsc::WaveShaper< T, WaveShaperType::Tanh >", "classjnsc_1_1WaveShaper_3_01T_00_01WaveShaperType_1_1Tanh_01_4.html", null ],
    [ "jnsc::WaveShaperProcessor< T, ShaperType >", "classjnsc_1_1WaveShaperProcessor.html", null ],
    [ "jnsc::utils::Xorshift32", "structjnsc_1_1utils_1_1Xorshift32.html", null ]
];